In [1]:
import geopandas as gpd
from sqlalchemy import create_engine

# 1. Connect to the database
cloud_engine = create_engine(
    "postgresql://postgres:postgres@127.0.0.1:5432/mwamko"
)

# 2. Function to load table from PostGIS as GeoDataFrame
def load_postgis_table(table_name, geom_col="geom"):
    """
    Load a PostGIS table as GeoDataFrame.
    """
    gdf = gpd.read_postgis(
        f"SELECT * FROM {table_name};",
        cloud_engine,
        geom_col=geom_col
    )
    return gdf

# 3. Load each table
constraints_gdf = load_postgis_table("constraints")
road_segments_gdf = load_postgis_table("road_segments")
vertices_gdf = load_postgis_table("road_segments_vertices_pgr")

# 4. Export to GeoJSON
constraints_gdf.to_file("/Users/georgeodero/mwamko-ai/datasets/processed/constraints.geojson", driver="GeoJSON")
road_segments_gdf.to_file("/Users/georgeodero/mwamko-ai/datasets/processed/road_segments.geojson", driver="GeoJSON")
vertices_gdf.to_file("/Users/georgeodero/mwamko-ai/datasets/processed/road_segments_vertices_pgr.geojson", driver="GeoJSON")

constraints_gdf.head()

,constraint_type,priority_level,county_id,active_until,geom
0,STATIC_DRAINAGE_NETWORK,10,Taita_Taveta,None,"POLYGON ((38.48333 -2.975, 38.49167 -2.975, 38..."
1,STATIC_DRAINAGE_NETWORK,10,Taita_Taveta,None,"POLYGON ((38.51667 -2.975, 38.54167 -2.975, 38..."
2,STATIC_DRAINAGE_NETWORK,10,Taita_Taveta,None,"POLYGON ((38.46667 -2.98333, 38.48333 -2.98333..."
3,STATIC_DRAINAGE_NETWORK,10,Taita_Taveta,None,"POLYGON ((38.49167 -2.98333, 38.51667 -2.98333..."
4,STATIC_DRAINAGE_NETWORK,10,Taita_Taveta,None,"POLYGON ((38.45 -2.99167, 38.46667 -2.99167, 3..."

In [2]:
road_segments_gdf.head()

,id,road_class,surface_type,length_km,base_maxspeed_kmh,cost,is_blocked,final_cost,geom,source,target
0,502298631,track,dirt,1.144575,20.0,3.433725,False,3.433725,"LINESTRING (38.30726 -3.56813, 38.30713 -3.567...",1,1
1,496647007,track,dirt,2.334191,20.0,7.002572,False,7.002572,"LINESTRING (38.24848 -3.363, 38.24942 -3.36327...",21,21
2,514903438,track,dirt,0.233879,20.0,0.701636,False,0.701636,"LINESTRING (38.38684 -3.50943, 38.38697 -3.509...",74,74
3,487366079,unclassified,unpaved,1.424784,50.0,1.709740,False,1.709740,"LINESTRING (38.36101 -3.35566, 38.36109 -3.355...",183,183
4,514788771,unclassified,unpaved,0.416595,50.0,0.499914,False,0.499914,"LINESTRING (38.3761 -3.51482, 38.37609 -3.5148...",197,197

In [3]:
vertices_gdf.head()

     id                       geom   x_coord  y_coord
0  9892  POINT (38.67146 -3.84911)  38.67146 -3.84911
1  9892   POINT (38.67149 -3.8491)  38.67149 -3.84910
2  9892  POINT (38.67152 -3.84909)  38.67152 -3.84909
3  9892  POINT (38.67155 -3.84907)  38.67155 -3.84907
4  9892  POINT (38.67157 -3.84905)  38.67157 -3.84905